### ISSUE TITLE
Plugin crashes FFPD

### ISSUE THREAD

**Issue by licensed2hench** [FalconChristmas/fpp-midi#1]
When I install the plugin I get the following message and FPP stops working.

"Abnormal Conditions - May Cause Poor Performance"
"FPPD Daemon is not running"

Restarting and Rebooting do not fix the issue.
Removing the plugin restores it to normal operation

I removed all other plugins, just in case, same issue.

Here is my Version Info 
FPP Version: 5.3.1
Platform: Raspberry Pi (Pi 3 Model B+)
FPP OS Build: v5.0
OS Version: Raspbian GNU/Linux 10 (buster)
Kernel Version: 5.10.52-v7+
Local Git Version: 8aaa6e2

Am I doing something wrong? Do I need to configure or set up something before installing the plugin?
I looked for more documentation on the plugin but didn't find anything

It did detect the USB Midi controller keyboard I plugged in and listed it on the plug in configuration page.
But it didn't see any events when I pressed any keys, but I suspect this is because FFPD wasn't running?
(clicking the enable box didn't seem to have any effect)

**Comment by licensed2hench** [comment]
Updated to 5.10.63-v7+
Local Git Version: a4ea8d3
I am no longer getting the error messages and FFPD seems to be running properly with the plug in installed.
It is still not seeing any events from the midi keyboard (enable checkbox is checked).
So I am not sure if it is working or not. 
I will give it a try and see if I can get it to trigger some commands from midi key press.

**Comment by licensed2hench** [comment]
I was able to add and save commands.
I created a command and added a second empty command requiring reboot
Upon rebooting I got the same error message.
Removing the second empty command line and rebooting seemed to fix the issue.
I also began to see messages from the midi keyboard.
(conclusion the plug in does not like empty command lines)

**Comment by licensed2hench** [comment]
It seems to be working now. I was able to map a key press to a next item in playlist command.
(I had to use the same hex notation format, in this case, "Note On" "=" "0x35")
I will keep playing with it :)

**Comment by licensed2hench** [comment]
If the data in the conditions filed is not formatted correctly or is missing it ill cause FFPD to crash.
Example "0x47" works "B4" does not.

**Comment by patdelaney** [comment]
This is not happening in FPPV8. I am closing
